export const ADD_TO_CART = "ADD_TO_CART";
export const REMOVE_FROM_CART = "REMOVE_FROM_CART";
export const ADJUST_QTY = 'ADJUST_QTY';
export const LOAD_CURRENT_ITEMS = 'LOAD_CURRENT_ITEMS';
export const CHANGE_CURRENCY = 'CHANGE_CURRENCY';
export const CHANGE_CATEGORY = 'CHANGE_CATEGORY';